# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c431bb39509bcb5467ecc0393d70dd6c881ab4a0b15e74b100031ac8864554ddc2b46b0d8c9697440e713bdc784535176e35e5ec87da6e58dac2f8438e869a7

test:
  secret_key_base: d46f2b3dd5627d2e6351c285f723dbd12c3e99624a5f1999cf3f961cd19d59e00890bfca795e4fb421e6d0562025bdbfea4469d5b0c41df417bb8d966ab9f4b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
