# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a85551beec1713da35fc2ba761e5ab737eb2ff109c70eb97ff22c1a8431144a1dc9bb210757bd0f99901af8004f09a39aac3ceed69770edeb7090fd3a8a5acfe

test:
  secret_key_base: 6cb67247888f92b40cdc5f8d03a7892b449a96e9a85901c412fcf042d4017c4941d2170c6dabb9e1cebc1d32ad1cc014343bfb6472b589aff5237626cb9fdc5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
