#!/usr/bin/env ruby
#Jon Allen
#CSCI 465
#Demonstration of spaghetti code generated by waiting 
#too long to start an assignment

$chances = 10     #number of chances a user has to guess
$ended = false    #used for while loop to keep game running
$empty = false    #flips when we've removed too many words
$target = "0"     #set to 0 until we choose a word
$uptarget = "0"   #the uppercase version of the target for case insensitivity
$letters = []     #printing out the game lines
$won = false      #used for victory condition

#get word length and set it to range
puts "Enter word length between 5 and 20: "
length = gets.to_i
if length < 5 then length = 5 end
if length > 20 then length = 20 end

#set up letters array for printing _ when letter is uncovered
for i in 0..length-1
  $letters[i] = '_'
end

#read words in then split them into an array for removal
words = IO.read("words").split("\n")
words.keep_if {|x| x.length == length}

#used to keep track of user guesses
$guesses = Array.new

#keeps track of user guesses and decrements users chances
def take_guess(letter)
  if letter.length > 1 then
    puts "Enter a single character, try again: "
    return false
  elsif $guesses.include?(letter) || $guesses.include?(letter.upcase) || $guesses.include?(letter.downcase) then
    puts "Already guessed that letter, try again: "
    return false
  else
    $guesses.push(letter)
    $guesses.push(letter.upcase)
    $guesses.push(letter.downcase)
    $chances = $chances-1
    if $chances == 0 then
      $ended = true
      return false
    end
    return true
  end
end

#used to remove workds until we pick the actual word
def check_words(letter, words2)
  temp = []
  temp = words2.map do |x| x.dup end
  words2.map! {|x| if x =~ /#{letter}/ then nil else x end}.compact!
  if words2.any? then #if the array is empty then we removed to many
    $empty = false 
    return words2
  else
    $empty = true
    return temp
  end
end

#print out either _ or a character in a word
def print_results(length)
  puts "Current Results"
  $won = true
  for i in 0..length-1
    if $guesses.include?($target[i]) or $guesses.include?($uptarget[i]) then
      puts $target[i]
    else
      puts "_"
      $won = false
    end
  end
  puts "Guesses left: #{$chances}"
end

while !($ended) do
  puts "enter your guess: "
  guess = gets.chomp
  if take_guess(guess) then
    if $target == "0" then
      temp = []
      temp = check_words(guess, words)
      if $empty then #use empty to see if we need to rebuild the array
        words = temp.map do |x| x.dup end
        $target = words[0]
        $uptarget = words[0].upcase
        puts $uptarget
        $uptarget = $uptarget.split(//)
        $target = $target.split(//)
      end
    end
  end
  print_results(length)
  if $won == true then
    puts "CONGRATS YOU ARE A WINNER!"
  end

end
